#!/usr/bin/env python3

import queue, threading, os, time
import fnmatch
from collections import Counter
import argparse
import shutil


parser = argparse.ArgumentParser(description='Process some integers.')

parser.add_argument('src', help='source file or directory')
parser.add_argument('dest', help='destination file or directory')
parser.add_argument('-v', help='verbose mode output error')
parser.add_argument('-t', type=int, default=2, help='define number thread default is 2')

args = parser.parse_args()

srcPath = args.src
destPath = args.dest
verbose = args.v
thread = args.t

fileQueue = queue.Queue()

class ThreadedCopy:
    totalFiles = 0
    copyCount = 0
    totalError = 0
    lock = threading.Lock()

    def __init__(self, srcPath, destPath, verbose, thread):
        self.srcPath = srcPath
        self.destPath = destPath
        self.verbose = verbose
        self.thread = thread

        allFiles = self.findFiles(self.srcPath)
        if not os.path.exists(self.destPath):
            os.mkdir(self.destPath)

        self.totalFiles = len(allFiles)

        print("{} files to copy.".format(self.totalFiles))
        self.threadWorkerCopy(allFiles)


    def findFiles(self, directory, pattern='*'):
        if not os.path.exists(directory):
            raise ValueError("Directory not found {}".format(directory))

        matches = []
        for root, dirnames, filenames in os.walk(directory):
            for filename in filenames:
                full_path = os.path.join(root, filename)
                if fnmatch.filter([full_path], pattern):
                    matches.append(os.path.join(root, filename))
        return matches

    def CopyWorker(self):
        while True:
            fileName = fileQueue.get()

            destPathClear = self.pathClean(destPath+fileName, destPath)

            try:
                os.makedirs(os.path.dirname(destPathClear))
            except FileExistsError:
                pass

            try:
                shutil.copy(fileName, os.path.dirname(destPathClear))
            except PermissionError as e:
                if self.verbose:
                    print(e)
                self.totalError += 1

            fileQueue.task_done()
            with self.lock:
                self.copyCount += 1
                percent = (self.copyCount * 100) / self.totalFiles
                if percent > 1:
                    total_time = (time.time() - self.start_time)
                    print("\033[F\033[K{} percent copied. {}/{} Error:{} WorkThread:{} TotalTime:{}s".format(percent, self.copyCount, self.totalFiles, self.totalError, self.thread, round(total_time,2)))
                else:
                    print("\033[F\033[K{} percent copied. {}/{} Error:{} WorkThread:{}".format(percent, self.copyCount, self.totalFiles, self.totalError, self.thread))

    def pathClean(self, stringPath, destPath):
        workPath = []

        for string in stringPath.split("/"):
            if string not in workPath:
             workPath.append(string)

        for string in destPath.split("/"):
            if string in workPath:
                workPath.remove(string)

        outFile = "{}/{}".format(self.destPath, "/".join(workPath[1:]))
        return outFile

    def threadWorkerCopy(self, fileNameList):
        self.start_time = time.time()
        for i in range(self.thread):
            t = threading.Thread(target=self.CopyWorker)
            t.daemon = True
            t.start()
        for fileName in fileNameList:
            fileQueue.put(fileName)
        fileQueue.join()

ThreadedCopy(srcPath, destPath, verbose, thread)
